---
# Copy over ssl certs
- name: Copy ssl certs to directory
  copy: src={{item}}
        dest={{ssl_key_dir}}
        owner=root
        group=root
        mode=0600
  with_items:
   - "{{ssl_key_loc}}"
  tags:
   - ssl-keys

- name: Ensure secure permissions
  file: path={{ssl_key_dir}}
        owner=root
        group=root
        mode=0600
        recurse=yes
  tags: 
   - ssl-keys
